server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo?currentSchema=private2
    username: postgres
    password: raviraj

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
 
security:
   jwt:
        secret: ${JWT_SECRET:kdfasdfiefeofdfjajoijfewfadfnsdfnfd}
        issuer: ${JWT_ISSUER:api.substring.com}
        access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:3600}    
        refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:86400}
        refresh-token-cookie-name: ${JWT_REFRESH_COOKIE_NAME:refreshToken}
        cookie-secure: ${JWT_COOKIE_SECURE:true}
        cookie-http-only: ${JWT_COOKIE_HTTP_ONLY:true}
        cookie-same-site: ${JWT_COOKIE_SAME_SITE:lax}
      